const keys = [
  '<sup>~</sup> <sub>`</sub>',
  '<sup>!</sup> 1',
  '<sup>@</sup> 2',
  '<sup>#</sup> 3',
  '<sup>$</sup> 4',
  '<sup>%</sup> 5',
  '<sup>^</sup> 6',
  '<sup>&</sup> 7',
  '<sup>*</sup> 8',
  '<sup>(</sup> 9',
  '<sup>)</sup> 0',
  '<sup>&ndash;</sup> -',
  '<sup>+</sup> =',
  'Backspace',
  'Tab',
  'Q',
  'W',
  'E',
  'R',
  'T',
  'Y',
  'U',
  'I',
  'O',
  'P',
  '<sup>{</sup> [',
  '<sup>}</sup> ]',
  'Del',
  'Caps Lock',
  'A',
  'S',
  'D',
  'F',
  'G',
  'H',
  'J',
  'K',
  'L',
  '<sup>:</sup> <sub>;</sub>',
  '<sup>"</sup> <sub>\'</sub>',
  'Enter',
  '<span class="visually-hidden">Left </span>Shift',
  '<sup>|</sup> \\',
  'Z',
  'X',
  'C',
  'V',
  'B',
  'N',
  'M',
  '<sup><</sup> ,',
  '<sup>></sup> .',
  '<sup>?</sup> /',
  '&#9650;',
  '<span class="visually-hidden">Right </span>Shift',
  '<span class="visually-hidden">Left </span>Ctrl',
  'Win',
  '<span class="visually-hidden">Left </span>Alt',
  ' ',
  '<span class="visually-hidden">Right </span>Alt',
  '<span class="visually-hidden">Right </span>Ctrl',
  '&#9668;',
  '&#9660;',
  '&#9658;',
];

export default keys;
