const keyboard = {
  en: {
    default: {
      '`': '`',
      '01': '1',
      '02': '2',
      '03': '3',
      '04': '4',
      '05': '5',
      '06': '6',
      '07': '7',
      '08': '8',
      '09': '9',
      '00': '0',
      '-': '-',
      '=': '=',
      Backspace: 'Backspace',
      Tab: 'Tab',
      q: 'q',
      w: 'w',
      e: 'e',
      r: 'r',
      t: 't',
      y: 'y',
      u: 'u',
      i: 'i',
      o: 'o',
      p: 'p',
      '[': '[',
      ']': ']',
      Delete: 'Delete',
      CapsLock: 'Caps Lock',
      a: 'a',
      s: 's',
      d: 'd',
      f: 'f',
      g: 'g',
      h: 'h',
      j: 'j',
      k: 'k',
      l: 'l',
      ';': ';',
      '\'': '\'',
      Enter: 'Enter',
      ShifLeft: 'Shift<span class="visually-hidden">Left</span>',
      '\\': '\\',
      z: 'z',
      x: 'x',
      c: 'c',
      v: 'v',
      b: 'b',
      n: 'n',
      m: 'm',
      ',': ',',
      '.': '.',
      '/': '/',
      ArrowUp: '▲',
      ShifRight: 'Shift<span class="visually-hidden">Right</span>',
      ControlLeft: 'C<span class="visually-hidden">on</span>tr<span class="visually-hidden">o</span>l<span class="visually-hidden">Left</span>',
      OS: 'Win',
      AltLeft: 'Alt<span class="visually-hidden">Left</span>',
      ' ': ' ',
      AltRight: 'Alt<span class="visually-hidden">Right</span>',
      ControlRight: 'C<span class="visually-hidden">on</span>tr<span class="visually-hidden">o</span>l<span class="visually-hidden">Right</span>',
      ArrowLeft: '◄',
      ArrowDown: '▼',
      ArrowRight: '►',
    },
    alternative: {
      '~': '~',
      '!': '!',
      '@': '@',
      '#': '#',
      $: '$',
      '%': '%',
      '^': '^',
      '&': '&',
      '*': '*',
      '(': '(',
      ')': ')',
      _: '_',
      '+': '+',
      Backspace: 'Backspace',
      Tab: 'Tab',
      Q: 'Q',
      W: 'W',
      E: 'E',
      R: 'R',
      T: 'T',
      Y: 'Y',
      U: 'U',
      I: 'I',
      O: 'O',
      P: 'P',
      '{': '{',
      '}': '}',
      Delete: 'Delete',
      CapsLock: 'Caps Lock',
      A: 'A',
      S: 'S',
      D: 'D',
      F: 'F',
      G: 'G',
      H: 'H',
      J: 'J',
      K: 'K',
      L: 'L',
      ':': ':',
      '"': '"',
      Enter: 'Enter',
      ShifLeft: 'Shift<span class="visually-hidden">Left</span>',
      '|': '|',
      Z: 'Z',
      X: 'X',
      C: 'C',
      V: 'V',
      B: 'B',
      N: 'N',
      M: 'M',
      '<': '<',
      '>': '>',
      '?': '?',
      ArrowUp: '▲',
      ShifRight: 'Shift<span class="visually-hidden">Right</span>',
      ControlLeft: 'C<span class="visually-hidden">on</span>tr<span class="visually-hidden">o</span>l<span class="visually-hidden">Left</span>',
      OS: 'Win',
      AltLeft: 'Alt<span class="visually-hidden">Left</span>',
      ' ': ' ',
      AltRight: 'Alt<span class="visually-hidden">Right</span>',
      ControlRight: 'C<span class="visually-hidden">on</span>tr<span class="visually-hidden">o</span>l<span class="visually-hidden">Right</span>',
      ArrowLeft: '◄',
      ArrowDown: '▼',
      ArrowRight: '►',
    },
    capslock: {
      '`': '`',
      '01': '1',
      '02': '2',
      '03': '3',
      '04': '4',
      '05': '5',
      '06': '6',
      '07': '7',
      '08': '8',
      '09': '9',
      '00': '0',
      '-': '-',
      '=': '=',
      Backspace: 'Backspace',
      Tab: 'Tab',
      Q: 'Q',
      W: 'W',
      E: 'E',
      R: 'R',
      T: 'T',
      Y: 'Y',
      U: 'U',
      I: 'I',
      O: 'O',
      P: 'P',
      '[': '[',
      ']': ']',
      Delete: 'Delete',
      CapsLock: 'Caps Lock',
      A: 'A',
      S: 'S',
      D: 'D',
      F: 'F',
      G: 'G',
      H: 'H',
      J: 'J',
      K: 'K',
      L: 'L',
      ';': ';',
      '\'': '\'',
      Enter: 'Enter',
      ShifLeft: 'Shift<span class="visually-hidden">Left</span>',
      '\\': '\\',
      Z: 'Z',
      X: 'X',
      C: 'C',
      V: 'V',
      B: 'B',
      N: 'N',
      M: 'M',
      ',': ',',
      '.': '.',
      '/': '/',
      ArrowUp: '▲',
      ShifRight: 'Shift<span class="visually-hidden">Right</span>',
      ControlLeft: 'C<span class="visually-hidden">on</span>tr<span class="visually-hidden">o</span>l<span class="visually-hidden">Left</span>',
      OS: 'Win',
      AltLeft: 'Alt<span class="visually-hidden">Left</span>',
      ' ': ' ',
      AltRight: 'Alt<span class="visually-hidden">Right</span>',
      ControlRight: 'C<span class="visually-hidden">on</span>tr<span class="visually-hidden">o</span>l<span class="visually-hidden">Right</span>',
      ArrowLeft: '◄',
      ArrowDown: '▼',
      ArrowRight: '►',
    },
  },
  ru: {
    default: {
      ё: 'ё',
      '01': '1',
      '02': '2',
      '03': '3',
      '04': '4',
      '05': '5',
      '06': '6',
      '07': '7',
      '08': '8',
      '09': '9',
      '00': '0',
      '-': '-',
      '=': '=',
      Backspace: 'Backspace',
      Tab: 'Tab',
      й: 'й',
      ц: 'ц',
      у: 'у',
      к: 'к',
      е: 'е',
      н: 'н',
      г: 'г',
      ш: 'ш',
      щ: 'щ',
      з: 'з',
      х: 'х',
      ъ: 'ъ',
      Delete: 'Delete',
      CapsLock: 'Caps Lock',
      ф: 'ф',
      ы: 'ы',
      в: 'в',
      а: 'а',
      п: 'п',
      р: 'р',
      о: 'о',
      л: 'л',
      д: 'д',
      ж: 'ж',
      э: 'э',
      Enter: 'Enter',
      ShifLeft: 'Shift<span class="visually-hidden">Left</span>',
      '\\': '\\',
      я: 'я',
      ч: 'ч',
      с: 'с',
      м: 'м',
      и: 'и',
      т: 'т',
      ь: 'ь',
      б: 'б',
      ю: 'ю',
      '.': '.',
      ArrowUp: '▲',
      ShifRight: 'Shift<span class="visually-hidden">Right</span>',
      ControlLeft: 'C<span class="visually-hidden">on</span>tr<span class="visually-hidden">o</span>l<span class="visually-hidden">Left</span>',
      OS: 'Win',
      AltLeft: 'Alt<span class="visually-hidden">Left</span>',
      ' ': ' ',
      AltRight: 'Alt<span class="visually-hidden">Right</span>',
      ControlRight: 'C<span class="visually-hidden">on</span>tr<span class="visually-hidden">o</span>l<span class="visually-hidden">Right</span>',
      ArrowLeft: '◄',
      ArrowDown: '▼',
      ArrowRight: '►',
    },
    alternative: {
      Ё: 'Ё',
      '!': '!',
      '"': '"',
      '№': '№',
      ';': ';',
      '%': '%',
      ':': ':',
      '?': '?',
      '*': '*',
      '(': '(',
      ')': ')',
      _: '_',
      '+': '+',
      Backspace: 'Backspace',
      Tab: 'Tab',
      Й: 'Й',
      Ц: 'Ц',
      У: 'У',
      К: 'К',
      Е: 'Е',
      Н: 'Н',
      Г: 'Г',
      Ш: 'Ш',
      Щ: 'Щ',
      З: 'З',
      Х: 'Х',
      Ъ: 'Ъ',
      Delete: 'Delete',
      CapsLock: 'Caps Lock',
      Ф: 'Ф',
      Ы: 'Ы',
      В: 'В',
      А: 'А',
      П: 'П',
      Р: 'Р',
      О: 'О',
      Л: 'Л',
      Д: 'Д',
      Ж: 'Ж',
      Э: 'Э',
      Enter: 'Enter',
      ShifLeft: 'Shift<span class="visually-hidden">Left</span>',
      '/': '/',
      Я: 'Я',
      Ч: 'Ч',
      С: 'С',
      М: 'М',
      И: 'И',
      Т: 'Т',
      Ь: 'Ь',
      Б: 'Б',
      Ю: 'Ю',
      ',': ',',
      ArrowUp: '▲',
      ShifRight: 'Shift<span class="visually-hidden">Right</span>',
      ControlLeft: 'C<span class="visually-hidden">on</span>tr<span class="visually-hidden">o</span>l<span class="visually-hidden">Left</span>',
      OS: 'Win',
      AltLeft: 'Alt<span class="visually-hidden">Left</span>',
      ' ': ' ',
      AltRight: 'Alt<span class="visually-hidden">Right</span>',
      ControlRight: 'C<span class="visually-hidden">on</span>tr<span class="visually-hidden">o</span>l<span class="visually-hidden">Right</span>',
      ArrowLeft: '◄',
      ArrowDown: '▼',
      ArrowRight: '►',
    },
    capslock: {
      Ё: 'Ё',
      '01': '1',
      '02': '2',
      '03': '3',
      '04': '4',
      '05': '5',
      '06': '6',
      '07': '7',
      '08': '8',
      '09': '9',
      '00': '0',
      '-': '-',
      '=': '=',
      Backspace: 'Backspace',
      Tab: 'Tab',
      Й: 'Й',
      Ц: 'Ц',
      У: 'У',
      К: 'К',
      Е: 'Е',
      Н: 'Н',
      Г: 'Г',
      Ш: 'Ш',
      Щ: 'Щ',
      З: 'З',
      Х: 'Х',
      Ъ: 'Ъ',
      Delete: 'Delete',
      CapsLock: 'Caps Lock',
      Ф: 'Ф',
      Ы: 'Ы',
      В: 'В',
      А: 'А',
      П: 'П',
      Р: 'Р',
      О: 'О',
      Л: 'Л',
      Д: 'Д',
      Ж: 'Ж',
      Э: 'Э',
      Enter: 'Enter',
      ShifLeft: 'Shift<span class="visually-hidden">Left</span>',
      '\\': '\\',
      Я: 'Я',
      Ч: 'Ч',
      С: 'С',
      М: 'М',
      И: 'И',
      Т: 'Т',
      Ь: 'Ь',
      Б: 'Б',
      Ю: 'Ю',
      '.': '.',
      ArrowUp: '▲',
      ShifRight: 'Shift<span class="visually-hidden">Right</span>',
      ControlLeft: 'C<span class="visually-hidden">on</span>tr<span class="visually-hidden">o</span>l<span class="visually-hidden">Left</span>',
      OS: 'Win',
      AltLeft: 'Alt<span class="visually-hidden">Left</span>',
      ' ': ' ',
      AltRight: 'Alt<span class="visually-hidden">Right</span>',
      ControlRight: 'C<span class="visually-hidden">on</span>tr<span class="visually-hidden">o</span>l<span class="visually-hidden">Right</span>',
      ArrowLeft: '◄',
      ArrowDown: '▼',
      ArrowRight: '►',
    },
  },
  map: {
    ruEnDefault: {
      ё: '`',
      й: 'q',
      ц: 'w',
      у: 'e',
      к: 'r',
      е: 't',
      н: 'y',
      г: 'u',
      ш: 'i',
      щ: 'o',
      з: 'p',
      х: '[',
      ъ: ']',
      ф: 'a',
      ы: 's',
      в: 'd',
      а: 'f',
      п: 'g',
      р: 'h',
      о: 'j',
      л: 'k',
      д: 'l',
      ж: ';',
      э: '\'',
      я: 'z',
      ч: 'x',
      с: 'c',
      м: 'v',
      и: 'b',
      т: 'n',
      ь: 'm',
      б: ',',
      ю: '.',
      '.': '/',
    },
    ruEnAlternative: {
      Ё: '~',
      '"': '@',
      '№': '#',
      ';': '$',
      ':': '^',
      '?': '&',
      Й: 'Q',
      Ц: 'W',
      У: 'E',
      К: 'R',
      Е: 'T',
      Н: 'Y',
      Г: 'U',
      Ш: 'I',
      Щ: 'O',
      З: 'P',
      Х: '{',
      Ъ: '}',
      Ф: 'A',
      Ы: 'S',
      В: 'D',
      А: 'F',
      П: 'G',
      Р: 'H',
      О: 'J',
      Л: 'K',
      Д: 'L',
      Ж: ':',
      Э: '"',
      '/': '|',
      Я: 'Z',
      Ч: 'X',
      С: 'C',
      М: 'V',
      И: 'B',
      Т: 'N',
      Ь: 'M',
      Б: '<',
      Ю: '>',
      ',': '?',
    },
    ruEnCapslock: {
      Ё: '`',
      Й: 'Q',
      Ц: 'W',
      У: 'E',
      К: 'R',
      Е: 'T',
      Н: 'Y',
      Г: 'U',
      Ш: 'I',
      Щ: 'O',
      З: 'P',
      Х: '[',
      Ъ: ']',
      Ф: 'A',
      Ы: 'S',
      В: 'D',
      А: 'F',
      П: 'G',
      Р: 'H',
      О: 'J',
      Л: 'K',
      Д: 'L',
      Ж: ';',
      Э: '\'',
      Я: 'Z',
      Ч: 'X',
      С: 'C',
      М: 'V',
      И: 'B',
      Т: 'N',
      Ь: 'M',
      Б: ',',
      Ю: '.',
      '.': '/',
    },
  },
  layout: 'en',
  capslock: 'off',
  shift: 'off',
};

export default keyboard;
